// 하려는 작업의 이름을 명시하기 위해 여기다가 써주는 것임
export const REQUEST_DATA_FROM_SPRING = 'REQUEST_DATA_FROM_SPRING'
export const REQUEST_RANDOM_MONSTER = 'REQUEST_MONSTER_LIST_DATA_FROM_SPRING'
export const REQUEST_RANDOM_SHOP_ITEM = 'REQUEST_RANDOM_SHOP_ITEM'
export const REQUEST_CHARACTER_STATUS_DATA = 'REQUEST_CHARACTER_STATUS_DATA'
export const REQUEST_CHARACTER_INVENTORY = 'REQUEST_CHARACTER_INVENTORY'