export const REQUEST_DATA_FROM_SPRING = 'REQUEST_DATA_FROM_SPRING'
export const REQUEST_RANDOM_SHOP_ITEM = 'REQUEST_RANDOM_SHOP_ITEM'
export const REQUEST_INVENTORY_ITEMS = 'REQUEST_INVENTORY_ITEMS'
export const REQUEST_DEFAULT_CHARACTER_STATUS = 'REQUEST_DEFAULT_CHARACTER_STATUS'
export const REQUEST_DEFAULT_MONSTER_LIST = 'REQUEST_DEFAULT_MONSTER_LIST'
export const REQUEST_HUNDRED_MONSTER_LIST = 'REQUEST_HUNDRED_MONSTER_LIST'

