
server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_test_db?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    username: root
    password: eddi@123

  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update