export const REQUEST_DATA_FROM_SPRING = 'REQUEST_DATA_FROM_SPRING'
export const REQUEST_RANDOM_SHOP_ITEM = 'REQUEST_RANDOM_SHOP_ITEM'
export const REQUEST_MONSTER_LIST = 'REQUEST_MONSTER_LIST'
export const REQUEST_RANDOM_MONSTER = 'REQUEST_RANDOM_MONSTER'
export const REQUEST_CHARACTER_STATUS_FROM_SPRING = 'REQUEST_CHARACTER_STATUS_FROM_SPRING'
export const REQUEST_INVENTORY_ITEM = 'REQUEST_INVENTORY_ITEM'
export const REQUEST_CHARACTER_STATUS_UPDATE_FROM_SPRING = 'REQUEST_CHARACTER_STATUS_UPDATE_FROM_SPRING'

export const REQUEST_BOARD_LIST_FROM_SPRING = 'REQUEST_BOARD_LIST_FROM_SPRING'
export const REQUEST_BOARD_FROM_SPRING = 'REQUEST_BOARD_FROM_SPRING'

export const REQUEST_PRODUCT_LIST_FROM_SPRING = 'REQUEST_PRODUCT_LIST_FROM_SPRING'