export const REQUEST_DATA_FROM_SPRING = 'REQUEST_DATA_FROM_SPRING'
export const REQUEST_RANDOM_SHOP_ITEM = 'REQUEST_RANDOM_SHOP_ITEM'
export const REQUEST_MY_INVENTORY = 'REQUEST_MY_INVENTORY'
export const REQUEST_MANY_MONSTERS = 'REQUEST_MANY_MONSTERS'
export const REQUEST_DEFAULT_MONSTERS = 'REQUEST_DEFAULT_MONSTERS'
export const REQUEST_CHARACTER_STATUS = 'REQUEST_CHARACTER_STATUS'
export const REQUEST_EXP_TRADE_SYSTEM = 'REQUEST_EXP_TRADE_SYSTEM'

export const REQUEST_BOARD_LIST_FROM_SPRING = 'REQUEST_BOARD_LIST_FROM_SPRING'
export const REQUEST_BOARD_FROM_SPRING = 'REQUEST_BOARD_FROM_SPRING'

