export const REQUEST_CHARACTER_STATUS_DATA = 'REQUEST_CHARACTER_STATUS_DATA,'
export const REQUEST_MONSTER_DATA = 'REQUEST_MONSTER_DATA,'
export const REQUEST_STOCK_DATA = 'REQUEST_STOCK_DATA,'
export const REQUEST_INVENTORY_DATA = 'REQUEST_INVENTORY_DATA,'
export const REQUEST_EQUIPMENT_DATA = 'REQUEST_EQUIPMENT_DATA,'


