export const REQUEST_PLAYER_DATA_FROM_SPRING = 'REQUEST_PLAYER_DATA_FROM_SPRING,'
export const REQUEST_MONSTER_DATA = 'REQUEST_MONSTER_DATA,'
export const REQUEST_STOCK_DATA = 'REQUEST_STOCK_DATA,'


